version: '3.8'

services:
  fhir-anonymizer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - ./:/app
#    entrypoint: ["dotnet", "Microsoft.Health.Fhir.Anonymizer.R4.CommandLineTool.dll"]
