version: '3.8'

services:
  fhir-anonymizer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    entrypoint: ["dotnet", "Microsoft.Health.Fhir.Anonymizer.R4.CommandLineTool.dll"]
    command: ["anonymize", "-i", "/data/input/", "-o", "/data/output/", "-c", "/data/config/config.json", "-v"]
